name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.80.0"
          extended: true

      - name: Build
        run: |
          git config core.quotePath false
          hugo --minify

      - name: Check links
        id: check-links
        uses: peter-evans/link-checker@v1
        with:
          args: -r public -d public -x "https?:\/\/"

      - name: Fail on link errors
        run: exit ${{ steps.check-links.outputs.exit_code }}

      - name: Deploy on GitHub
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: ouuan/ouuan.github.io
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./public
          publish_branch: master
          commit_message: ${{ github.event.head_commit.message }}

      - name: Add ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_RSA_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy on Gitee
        run: |
          hugo --minify -b https://ouuan.gitee.io
          cd ..
          git clone git@gitee.com:ouuan/ouuan.git
          mv ouuan/.git .
          rm -r ouuan
          cp -r hugo-blog/public ouuan
          mv .git ouuan
          cd ouuan
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "${{ github.event.head_commit.message }}"
          git push -f

      - name: Rebuild on Gitee
        uses: yanglbme/gitee-pages-action@608fe766b5f34094dafd551d22b35003ee2b77b2
        with:
          gitee-username: ouuan
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: ouuan/ouuan
