name: Update Clicks

on:
  schedule:
    - cron: "*/3 * * * *"

jobs:
  update-clicks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.69.2"
          extended: true

      - name: Build
        run: |
          git config core.quotePath false
          hugo

      - name: Install requests
        run: pip install requests

      - run: python scripts/UpdateClicks.py

      - name: Commit
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git commit -am "Update Clicks"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: ${{ github.ref }}
